version: 2
updates:
  # Configuration for npm/yarn
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'enhancement'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    # Specify reviewers for pull requests
    reviewers:
      - 'Hudson-Pufferfish'
    # Group dependencies updates
    groups:
      nestjs:
        patterns:
          - '@nestjs*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'
      security:
        patterns:
          - 'bcrypt'
          - '@prisma/client'
          - 'prisma'
      validation:
        patterns:
          - 'class-validator'
          - 'class-transformer'
    # Ignore less critical dependencies
    ignore:
      # Keep dev dependencies on their current major version
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'prettier'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'jest'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ts-jest'
        update-types: ['version-update:semver-major']
    # Set the target branch
    target-branch: 'main'
    # Set the version requirements
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
