# Domain-specific labels
auth:
  - any:
      - 'apps/main-service/src/domain/auth/**/*'
      - 'apps/**/auth.guard.ts'
      - '**/jwt/**/*'

user:
  - any:
      - 'apps/main-service/src/domain/user/**/*'

property:
  - any:
      - 'apps/main-service/src/domain/property/**/*'

reservation:
  - any:
      - 'apps/main-service/src/domain/reservation/**/*'

category:
  - any:
      - 'apps/main-service/src/domain/category/**/*'

# Infrastructure labels
database:
  - any:
      - 'apps/**/prisma/**/*'
      - 'apps/**/database/**/*'
      - '**/migration.sql'
      - '**/schema.prisma'

api-docs:
  - any:
      - '**/swagger/**/*'
      - '**/*.dto.ts'

security:
  - any:
      - '**/guard/**/*'
      - '**/auth/**/*'
      - '**/jwt/**/*'

# Core infrastructure
core:
  - any:
      - 'apps/main-service/src/main.ts'
      - 'apps/*/src/app.module.ts'
      - '**/interceptor/**/*'
      - '**/decorator/**/*'

# Configuration files
config:
  - any:
      - '**/*.env'
      - '**/tsconfig*.json'
      - '.eslintrc.js'
      - '.prettierrc'
      - 'package.json'
      - 'yarn.lock'
      - 'commitlint.config.js'
      - 'lint-staged.config.js'

# CI/CD, GitHub, and Git workflow
workflow:
  - any:
      - '.github/**/*'
      - '.gitlab-ci.yml'
      - '.husky/**/*'
      - '.git/**/*'
      - '.gitignore'
      - '.gitattributes'

# Infrastructure & Deployment
infrastructure:
  - any:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '**/.dockerignore'
      - '**/kubernetes/**/*'
      - '**/helm/**/*'
      - '**/terraform/**/*'
      - '**/nginx/**/*'
      - '**/deploy/**/*'

# Testing
test:
  - any:
      - '**/*.spec.ts'
      - '**/*.e2e-spec.ts'
      - '**/test/**/*'
      - 'jest.config.js'

# Documentation
docs:
  - any:
      - '**/*.md'
      - '**/docs/**/*'
      - '**/README*'
