name: 'Mark stale PRs'
on:
  schedule:
    - cron: '0 0 * * *' # Run daily

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 7 days with no activity.'
          stale-pr-label: 'stale'
          days-before-pr-stale: 30
          days-before-pr-close: 7
