name: 'PR Size Labeler'
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          sizes: >
            {
              "XS": "0-299",
              "S": "300-999",
              "M": "1000-1999",
              "L": "2000-2999",
              "XL": "3000+"
            }
