name: 'PR Size Labeler'
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '300'
          s_label: 'size/S'
          s_max_size: '1000'
          m_label: 'size/M'
          m_max_size: '2000'
          l_label: 'size/L'
          l_max_size: '3000'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 3000 lines.
            Please consider splitting it into smaller PRs.
